### PR TITLE
JAMES-2586 implement dao for mailbox table

### PR DESCRIPTION
**Pull request by hungphan227**

### CODE REVIEW

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/user/PostgresMailboxId.java [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+        public PostgresMailboxId fromString(String serialized) {
+            return of(Long.parseLong(serialized));
+        }
+    }
+
+    public static PostgresMailboxId of(long value) {
+        return new PostgresMailboxId(value);
+    }
+
+    private final long value;
```
Comment (vttranlina) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/user/PostgresMailboxId.java:38]:
```suggestion
    private final UUID value;
```

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java [hunk 2]
```diff
@@ -0,0 +1,176 @@
...
+
+    @Override
+    public Mono<MailboxId> rename(Mailbox mailbox) {
+        Preconditions.checkNotNull(mailbox.getMailboxId(), "A mailbox we want to rename should have a defined mailboxId");
+
+        return postgresExecutor.dslContext()
+            .flatMap(dslContext -> Mono.from(dslContext.update(TABLE_NAME)
+                .set(MAILBOX_NAME, mailbox.getName())
+                .set(USER_NAME, mailbox.getUser().asString())
+                .set(MAILBOX_NAMESPACE, mailbox.getNamespace())))
```
Comment (vttranlina) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java:86]: NO `where` condition?

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java [hunk 3]
```diff
@@ -0,0 +1,176 @@
...
+            .thenReturn(mailbox.getMailboxId())
+            .onErrorResume(throwable -> {
+                if (throwable.getMessage().contains("duplicate key value violates unique constraint")) {
```
Comment (Arsnael) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java:89]: Could extract it into a method, to avoid duplicate error management (I see same block in create method)

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java [hunk 4]
```diff
@@ -0,0 +1,176 @@
...
+                    record.get(USER_NAME),
+                    record.get(MAILBOX_NAME),
+                    record.get(MAILBOX_UID_VALIDITY))))
+            .last()
+            .onErrorResume(NoSuchElementException.class, e -> Mono.empty());
+    }
+
+    @Override
+    public Flux<Mailbox> findMailboxWithPathLike(MailboxQuery.UserBound query) {
+        return null;
```
Comment (Arsnael) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java:137]: todo

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/table/PostgresMailboxTable.java [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+            .column(MAILBOX_NAMESPACE)
+            .column(MAILBOX_LAST_UID)
+            .column(MAILBOX_HIGHEST_MODSEQ)
+            .constraint(DSL.primaryKey(MAILBOX_ID))
+            .constraint(DSL.unique(MAILBOX_NAME, USER_NAME, MAILBOX_NAMESPACE))))
+        .enableRowLevelSecurity();
+
+//     PostgresIndex INDEX = PostgresIndex.name("subscription_user_index")
+//        .createIndexStep((dsl, indexName) -> dsl.createIndex(indexName)
+//            .on(TABLE_NAME, USER));
```
Comment (Arsnael) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/table/PostgresMailboxTable.java:55]: todo?

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java (hunk 2 above)
Comment (hungphan227) [reply mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java:86]: it is used to retrieve all mailboxes

File: mailbox/api/src/main/java/org/apache/james/mailbox/model/Mailbox.java [hunk 6]
```diff
@@ -138,7 +138,9 @@ public boolean isChildOf(Mailbox potentialParent, MailboxSession mailboxSession)
     public boolean equals(Object obj) {
         if (obj instanceof Mailbox) {
             Mailbox o = (Mailbox)obj;
-            return Objects.equals(id, o.getMailboxId());
+            return Objects.equals(id, o.getMailboxId())
+                && Objects.equals(path, o.path)
+                && Objects.equals(uidValidity, o.uidValidity);
```
Comment (chibenwa) [inline mailbox/api/src/main/java/org/apache/james/mailbox/model/Mailbox.java:143]: Danger zone.

Please do not alter core POJOs, unless you really know what you do.

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/PostgresMailboxTable.java [hunk 7]
```diff
@@ -0,0 +1,54 @@
...
+import java.util.UUID;
+
+import org.apache.james.backends.postgres.PostgresTable;
+import org.jooq.Field;
+import org.jooq.Record;
+import org.jooq.Table;
+import org.jooq.impl.DSL;
+import org.jooq.impl.SQLDataType;
+
+public interface PostgresMailboxTable {
```
Comment (chibenwa) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/PostgresMailboxTable.java:31]: Please inline this into the module

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/PostgresMailboxTable.java [hunk 8]
```diff
@@ -0,0 +1,54 @@
...
+            .column(MAILBOX_ID, SQLDataType.UUID)
+            .column(MAILBOX_NAME)
+            .column(MAILBOX_UID_VALIDITY)
+            .column(USER_NAME)
+            .column(MAILBOX_NAMESPACE)
+            .column(MAILBOX_LAST_UID)
+            .column(MAILBOX_HIGHEST_MODSEQ)
+            .constraint(DSL.primaryKey(MAILBOX_ID))
+            .constraint(DSL.unique(MAILBOX_NAME, USER_NAME, MAILBOX_NAMESPACE))))
+        .enableRowLevelSecurity();
```
Comment (chibenwa) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/PostgresMailboxTable.java:53]: Which column is used here to back row level security?

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java [hunk 9]
```diff
@@ -0,0 +1,165 @@
...
+
+    @Override
+    public Mono<Mailbox> create(MailboxPath mailboxPath, UidValidity uidValidity) {
+        return postgresExecutor.dslContext()
+            .flatMapMany(dslContext -> Mono.from(dslContext.insertInto(TABLE_NAME, MAILBOX_ID, MAILBOX_NAME, USER_NAME, MAILBOX_NAMESPACE, MAILBOX_UID_VALIDITY)
+                .values(PostgresMailboxId.generate().asUuid(), mailboxPath.getName(), mailboxPath.getUser().asString(), mailboxPath.getNamespace(), uidValidity.asLong())
+                .returningResult(MAILBOX_ID))
+                .map(record -> new Mailbox(mailboxPath, uidValidity, PostgresMailboxId.of(record.get(MAILBOX_ID)))))
+            .last()
+            .onErrorMap(throwable -> throwable.getMessage().contains(DUPLICATE_VIOLATION_MESSAGE),
```
Comment (chibenwa) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java:72]: What is the class of that exception?

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java [hunk 10]
```diff
@@ -0,0 +1,165 @@
...
+    @Inject
+    public PostgresMailboxDAOImpl(PostgresExecutor postgresExecutor) {
+        this.postgresExecutor = postgresExecutor;
+    }
+
+    @Override
+    public Mono<Mailbox> create(MailboxPath mailboxPath, UidValidity uidValidity) {
+        return postgresExecutor.dslContext()
+            .flatMapMany(dslContext -> Mono.from(dslContext.insertInto(TABLE_NAME, MAILBOX_ID, MAILBOX_NAME, USER_NAME, MAILBOX_NAMESPACE, MAILBOX_UID_VALIDITY)
+                .values(PostgresMailboxId.generate().asUuid(), mailboxPath.getName(), mailboxPath.getUser().asString(), mailboxPath.getNamespace(), uidValidity.asLong())
```
Comment (chibenwa) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java:68]: Allocate the postgresId to a variable and reuse it?
THis might require less network and less parsing...

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java [hunk 11]
```diff
@@ -0,0 +1,165 @@
...
+
+    private Mailbox generateMailbox(Record record) {
+        return new Mailbox(new MailboxPath(record.get(MAILBOX_NAMESPACE), Username.of(record.get(USER_NAME)), record.get(MAILBOX_NAME)),
+            sanitizeUidValidity(record.get(MAILBOX_UID_VALIDITY)), PostgresMailboxId.of(record.get(PostgresMailboxTable.MAILBOX_ID)));
+    }
+
+    private UidValidity sanitizeUidValidity(long uidValidity) {
+        if (UidValidity.isValid(uidValidity)) {
+            return UidValidity.of(uidValidity);
+        }
```
Comment (chibenwa) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java:162]:
```suggestion

```

With a brand new mailbox implementation we will not get any invalid UidValidity. Let's simplify.

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java [hunk 12]
```diff
@@ -0,0 +1,165 @@
...
+    }
+
+    @Override
+    public Flux<Mailbox> getAll() {
+        return postgresExecutor.dslContext()
+            .flatMapMany(dsl -> Flux.from(dsl.selectFrom(TABLE_NAME)))
+                .map(this::generateMailbox);
+    }
+
+    private Mailbox generateMailbox(Record record) {
```
Comment (chibenwa) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java:154]:
```suggestion
    private Mailbox asMailbox(Record record) {
```

We are not generating anything...

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java [hunk 13]
```diff
@@ -0,0 +1,165 @@
...
+                    .where(MAILBOX_NAME.like(pathLike)
+                        .and(USER_NAME.eq(query.getFixedUser().asString()))
+                        .and(MAILBOX_NAMESPACE.eq(query.getFixedNamespace()))))
+                .map(this::generateMailbox))
+            .filter(query::matches);
+    }
+
+    @Override
+    public Mono<Boolean> hasChildren(Mailbox mailbox, char delimiter) {
+        final String name = mailbox.getName() + delimiter + SQL_WILDCARD_CHAR;
```
Comment (chibenwa) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java:135]:
```suggestion
        String name = mailbox.getName() + delimiter + SQL_WILDCARD_CHAR;
```

File: mailbox/postgres/src/test/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOTest.java [hunk 14]
```diff
@@ -0,0 +1,217 @@
...
+import org.apache.james.mailbox.model.search.ExactName;
+import org.apache.james.mailbox.model.search.MailboxQuery;
+import org.apache.james.mailbox.model.search.PrefixedWildcard;
+import org.junit.jupiter.api.Test;
+
+import com.google.common.collect.ImmutableSet;
+
+import reactor.core.publisher.Mono;
+
+public abstract class PostgresMailboxDAOTest {
```
Comment (chibenwa) [inline mailbox/postgres/src/test/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOTest.java:42]: What's the point? It looks like a duplication of the MailboxMapper tests to me...

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/PostgresMailboxTable.java (hunk 8 above)
Comment (hungphan227) [reply mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/PostgresMailboxTable.java:53]:
```
return "SET app.current_domain = ''; ALTER TABLE " + tableName + " ADD DOMAIN varchar(255) not null DEFAULT current_setting('app.current_domain')::text;" +
            "ALTER TABLE " + tableName + " ENABLE ROW LEVEL SECURITY; " +
            "CREATE POLICY DOMAIN_" + tableName + "_POLICY ON " + tableName + " USING (DOMAIN = current_setting('app.current_domain')::text);";
```

line 72 in PostgresTableManager

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java (hunk 10 above)
Comment (hungphan227) [reply mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java:68]: less network??

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java [hunk 15]
```diff
@@ -0,0 +1,47 @@
...
+import org.apache.james.mailbox.model.Mailbox;
+import org.apache.james.mailbox.model.MailboxId;
+import org.apache.james.mailbox.model.MailboxPath;
+import org.apache.james.mailbox.model.UidValidity;
+import org.apache.james.mailbox.model.search.MailboxQuery;
+
+import reactor.core.publisher.Flux;
+import reactor.core.publisher.Mono;
+
+public interface PostgresMailboxDAO {
```
[the remark this answers is not in the document]
Comment (hungphan227) [reply mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java]: removed

File: mailbox/api/src/main/java/org/apache/james/mailbox/model/Mailbox.java (hunk 6 above)
Comment (hungphan227) [reply mailbox/api/src/main/java/org/apache/james/mailbox/model/Mailbox.java]: reverted change

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java (hunk 9 above)
Comment (hungphan227) [reply mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOImpl.java]: added

File: mailbox/postgres/src/test/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOTest.java (hunk 14 above)
Comment (hungphan227) [reply mailbox/postgres/src/test/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOTest.java]: removed

File: mailbox/postgres/src/test/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOTest.java [hunk 16]
```diff
@@ -19,28 +19,31 @@
...
+import org.junit.jupiter.api.BeforeEach;
 import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.RegisterExtension;
 
 import com.google.common.collect.ImmutableSet;
 
 import reactor.core.publisher.Mono;
 
-public abstract class PostgresMailboxDAOTest {
+public class PostgresMailboxDAOTest {
```
Comment (Arsnael) [inline mailbox/postgres/src/test/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOTest.java:46]: I think @chibenwa was saying to remove that test class, cause the test for MailboxMapper should be enough to cover the DAO underneath?

Comment (hungphan227) [reply mailbox/postgres/src/test/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOTest.java:46]: I remember I have removed it :((

Comment (hungphan227) [reply mailbox/postgres/src/test/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAOTest.java]: deleted

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
Need to rebase to solve conflicts after this: https://github.com/apache/james-project/pull/1787#pullrequestreview-1724265328

Please make sure to move your new classes to postgres subpath instead of jpa :)

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java [hunk 17]
```diff
@@ -0,0 +1,165 @@
...
+                if (records.size() == 0) {
+                    return Mono.error(new MailboxNotFoundException(mailbox.getMailboxId()));
+                } else {
+                    return Mono.just(mailbox.getMailboxId());
+                }
+            });
+    }
+
+    public Mono<Void> delete(MailboxId mailboxId) {
+        return postgresExecutor.dslContext()
```
Comment (vttranlina) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java:104]: Some util method in executor class make code less boilerplate :D 
```
return postgresExecutor.executeVoid(dslContext -> Mono.from(dslContext.deleteFrom(TABLE_NAME)
                .where(MAILBOX_ID.eq(((PostgresMailboxId) mailboxId).asUuid()))));
```

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java [hunk 18]
```diff
@@ -0,0 +1,165 @@
...
+            .flatMap(dslContext -> Mono.from(dslContext.deleteFrom(TABLE_NAME)
+                .where(MAILBOX_ID.eq(((PostgresMailboxId) mailboxId).asUuid()))))
+            .then();
+    }
+
+    public Mono<Mailbox> findMailboxByPath(MailboxPath mailboxPath) {
+        return postgresExecutor.dslContext()
```
Comment (vttranlina) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java:111]: what do you think about method `.limit(1)` of jooq?
Example

```java
Mono.from(dsl.selectFrom(TABLE_NAME)
                        .where(MAILBOX_NAME.eq(mailboxPath.getName())
                            .and(USER_NAME.eq(mailboxPath.getUser().asString()))
                            .and(MAILBOX_NAMESPACE.eq(mailboxPath.getNamespace())))
                        .limit(1))
                    .map(this::asMailbox);
```

Although (mailboxName + username + space) is unique, the using  `last` of Flux looks a bit risk

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java (hunk 17 above)
Comment (hungphan227) [reply mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java:104]: Is it necessary? I see that the amount of boilerplate it remove is very little

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java (hunk 18 above)
Comment (hungphan227) [reply mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java:111]: updated to remove last() function

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java (hunk 17 above)
Comment (chibenwa) [reply mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java:104]: Please do

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java (hunk 18 above)
Comment (vttranlina) [reply mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java:111]: I don't see the `.limit(1)` 
Do you think it is unnecessary?

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java (hunk 17 above)
Comment (hungphan227) [reply mailbox/postgres/src/main/java/org/apache/james/mailbox/jpa/mail/dao/PostgresMailboxDAO.java]: updated

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxDAO.java [hunk 19]
```diff
@@ -77,85 +76,74 @@ public Mono<Mailbox> create(MailboxPath mailboxPath, UidValidity uidValidity) {
...
+                    return Mono.just(mailbox.getMailboxId());
+                }
+            })
             .onErrorMap(e -> e instanceof DataAccessException && e.getMessage().contains(DUPLICATE_VIOLATION_MESSAGE),
                 throwable -> new MailboxExistsException(mailbox.getName()));
     }
 
-    private Mono<MailboxId> rename(Mailbox mailbox, DSLContext dslContext) {
+    private Mono<List<Record>> rename(Mailbox mailbox, DSLContext dslContext) {
         return Flux.from(dslContext.update(TABLE_NAME)
```
Comment (Arsnael) [inline mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxDAO.java:92]: I find the JOOQ doc not easy to navigate but... I'm finding strange an update on a record where we match the PK has to return a flux. Not possible to return a Mono? Returning a Mono<List<Record>> for a rename looks... rather strange to me

**Comment by Arsnael** [comment]
Please rebase as well and follow changes as well introduced in https://github.com/apache/james-project/pull/1790 :)

File: mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxDAO.java (hunk 19 above)
Comment (hungphan227) [reply mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxDAO.java]: fixed

**Comment by Arsnael** [comment]
```
04:50:52,993 [ERROR] /home/jenkins/workspace/james_ApacheJames_PR-1786/mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/PostgresMailboxModule.java:[55,13] cannot find symbol
04:50:52,993 [ERROR]   symbol:   method enableRowLevelSecurity()
04:50:52,993 [ERROR]   location: interface org.apache.james.backends.postgres.PostgresTable.RequireRowLevelSecurity
```

**Review by vttranlina — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]
